with src_historical_play_by_play as (
    select * from "football_play_by_play"."raw"."PLAY-BY-PLAY-CSV-STREAM"
)
select 
    concat(game_id, '-', drive, '-', play_id) as historical_play_id,
    play_id::text as play_id,
    game_id,
    old_game_id::text as old_game_id,
    home_team,
    away_team,
    season_type,
    week,
    posteam as possession_team,
    posteam_type as possession_team_type,
    defteam as defending_team,
    side_of_field,
    yardline_100 as yard_line_from_endzone,
    game_date,
    quarter_seconds_remaining,
    half_seconds_remaining,
    game_seconds_remaining,
    case game_half 
        when 'Half1' then 1 
        when 'Half2' then 2 
        when 'Overtime' then 3 
        else 0
    end as game_half,
    quarter_end,
    drive,
    COALESCE(TRY_TO_NUMBER(sp), 0)::boolean as score_on_play,
    qtr as quarter,
    down,
    COALESCE(TRY_TO_NUMBER(goal_to_go), 0)::boolean as goal_to_go,
    time as time_left_in_quarter,
    yrdln as current_field_position,
    ydstogo as yards_to_go,
    ydsnet as net_yards_gained_on_drive,
    desc as play_description,
    play_type,
    yards_gained,
    COALESCE(TRY_TO_NUMBER(shotgun), 0)::boolean as shotgun,
    COALESCE(TRY_TO_NUMBER(no_huddle), 0)::boolean as no_huddle,
    COALESCE(TRY_TO_NUMBER(qb_dropback), 0)::boolean as qb_dropback,
    COALESCE(TRY_TO_NUMBER(qb_kneel), 0)::boolean as qb_kneel,
    COALESCE(TRY_TO_NUMBER(qb_spike), 0)::boolean as qb_spike,
    COALESCE(TRY_TO_NUMBER(qb_scramble), 0)::boolean as qb_scramble,
    pass_length,
    pass_location,
    air_yards,
    yards_after_catch,
    run_location,
    run_gap,
    field_goal_result,
    kick_distance,
    extra_point_result,
    two_point_conv_result,
    home_timeouts_remaining,
    away_timeouts_remaining,
    COALESCE(TRY_TO_NUMBER(timeout), 0)::boolean as timeout_called,
    timeout_team,
    td_team,
    td_player_name,
    td_player_id,
    posteam_timeouts_remaining as possession_team_timeouts_remaining,
    defteam_timeouts_remaining as defending_team_timeouts_remaining,
    total_home_score,
    total_away_score,
    posteam_score as possession_team_score,
    defteam_score as defending_team_score,
    score_differential,
    posteam_score_post as possession_team_score_post_play,
    defteam_score_post as defending_team_score_post_play,
    score_differential_post as score_differential_post_play,
    no_score_prob as no_score_rest_of_half_prob,
    opp_fg_prob,
    opp_safety_prob,
    opp_td_prob,
    fg_prob,
    safety_prob,
    td_prob,
    extra_point_prob,
    two_point_conversion_prob,
    ep as expected_points,
    epa as expected_points_added,
    total_home_epa,
    total_away_epa,
    total_home_rush_epa,
    total_away_rush_epa,
    total_home_pass_epa,
    total_away_pass_epa,
    air_epa,
    yac_epa,
    comp_air_epa,
    comp_yac_epa,
    total_home_comp_air_epa,
    total_away_comp_air_epa,
    total_home_comp_yac_epa,
    total_away_comp_yac_epa,
    total_home_raw_air_epa,
    total_away_raw_air_epa,
    total_home_raw_yac_epa,
    total_away_raw_yac_epa,
    wp as possession_team_win_probability,
    def_wp as defensive_team_win_probability,
    home_wp home_team_win_probability,
    away_wp away_team_win_probability,
    wpa possession_team_win_probability_added,
    vegas_wpa,
    vegas_home_wpa,
    home_wp_post as home_wp_post_play,
    away_wp_post as away_wp_post_play,
    vegas_wp,
    vegas_home_wp,
    total_home_rush_wpa,
    total_away_rush_wpa,
    total_home_pass_wpa,
    total_away_pass_wpa,
    air_wpa,
    yac_wpa,
    comp_air_wpa,
    comp_yac_wpa,
    total_home_comp_air_wpa,
    total_away_comp_air_wpa,
    total_home_comp_yac_wpa,
    total_away_comp_yac_wpa,
    total_home_raw_air_wpa,
    total_away_raw_air_wpa,
    total_home_raw_yac_wpa,
    total_away_raw_yac_wpa,
    COALESCE(TRY_TO_NUMBER(punt_blocked), 0)::boolean as punt_blocked,
    COALESCE(TRY_TO_NUMBER(first_down_rush), 0)::boolean as first_down_rush,
    COALESCE(TRY_TO_NUMBER(first_down_pass), 0)::boolean as first_down_pass,
    COALESCE(TRY_TO_NUMBER(first_down_penalty), 0)::boolean as first_down_penalty,
    COALESCE(TRY_TO_NUMBER(third_down_converted), 0)::boolean as third_down_converted,
    COALESCE(TRY_TO_NUMBER(third_down_failed), 0)::boolean as third_down_failed,
    COALESCE(TRY_TO_NUMBER(fourth_down_converted), 0)::boolean as fourth_down_converted,
    COALESCE(TRY_TO_NUMBER(fourth_down_failed), 0)::boolean as fourth_down_failed,
    COALESCE(TRY_TO_NUMBER(incomplete_pass), 0)::boolean as incomplete_pass,
    COALESCE(TRY_TO_NUMBER(touchback), 0)::boolean as touchback,
    COALESCE(TRY_TO_NUMBER(interception), 0)::boolean as interception,
    COALESCE(TRY_TO_NUMBER(punt_inside_twenty), 0)::boolean as punt_inside_twenty,
    COALESCE(TRY_TO_NUMBER(punt_in_endzone), 0)::boolean as punt_in_endzone,
    COALESCE(TRY_TO_NUMBER(punt_out_of_bounds), 0)::boolean as punt_out_of_bounds,
    COALESCE(TRY_TO_NUMBER(punt_downed), 0)::boolean as punt_downed,
    COALESCE(TRY_TO_NUMBER(punt_fair_catch), 0)::boolean as punt_fair_catch,
    COALESCE(TRY_TO_NUMBER(kickoff_inside_twenty), 0)::boolean as kickoff_inside_twenty,
    COALESCE(TRY_TO_NUMBER(kickoff_in_endzone), 0)::boolean as kickoff_in_endzone,
    COALESCE(TRY_TO_NUMBER(kickoff_out_of_bounds), 0)::boolean as kickoff_out_of_bounds,
    COALESCE(TRY_TO_NUMBER(kickoff_downed), 0)::boolean as kickoff_downed,
    COALESCE(TRY_TO_NUMBER(kickoff_fair_catch), 0)::boolean as kickoff_fair_catch,
    COALESCE(TRY_TO_NUMBER(fumble_forced), 0)::boolean as fumble_forced,
    COALESCE(TRY_TO_NUMBER(fumble_not_forced), 0)::boolean as fumble_not_forced,
    COALESCE(TRY_TO_NUMBER(fumble_out_of_bounds), 0)::boolean as fumble_out_of_bounds,
    COALESCE(TRY_TO_NUMBER(solo_tackle), 0)::boolean as solo_tackle,
    COALESCE(TRY_TO_NUMBER(safety), 0)::boolean as safety,
    COALESCE(TRY_TO_NUMBER(penalty), 0)::boolean as penalty,
    COALESCE(TRY_TO_NUMBER(tackled_for_loss), 0)::boolean as tackled_for_loss,
    COALESCE(TRY_TO_NUMBER(fumble_lost), 0)::boolean as fumble_lost,
    COALESCE(TRY_TO_NUMBER(own_kickoff_recovery), 0)::boolean as own_kickoff_recovery,
    COALESCE(TRY_TO_NUMBER(own_kickoff_recovery_td), 0)::boolean as own_kickoff_recovery_td,
    COALESCE(TRY_TO_NUMBER(qb_hit), 0)::boolean as qb_hit,
    COALESCE(TRY_TO_NUMBER(rush_attempt), 0)::boolean as rush_attempt,
    COALESCE(TRY_TO_NUMBER(pass_attempt), 0)::boolean as pass_attempt,
    COALESCE(TRY_TO_NUMBER(sack), 0)::boolean as sack,
    COALESCE(TRY_TO_NUMBER(touchdown), 0)::boolean as touchdown,
    COALESCE(TRY_TO_NUMBER(pass_touchdown), 0)::boolean as pass_touchdown,
    COALESCE(TRY_TO_NUMBER(rush_touchdown), 0)::boolean as rush_touchdown,
    COALESCE(TRY_TO_NUMBER(return_touchdown), 0)::boolean as return_touchdown,
    COALESCE(TRY_TO_NUMBER(extra_point_attempt), 0)::boolean as extra_point_attempt,
    COALESCE(TRY_TO_NUMBER(two_point_attempt), 0)::boolean as two_point_attempt,
    COALESCE(TRY_TO_NUMBER(field_goal_attempt), 0)::boolean as field_goal_attempt,
    COALESCE(TRY_TO_NUMBER(kickoff_attempt), 0)::boolean as kickoff_attempt,
    COALESCE(TRY_TO_NUMBER(punt_attempt), 0)::boolean as punt_attempt,
    COALESCE(TRY_TO_NUMBER(fumble), 0)::boolean as fumble,
    COALESCE(TRY_TO_NUMBER(complete_pass), 0)::boolean as complete_pass,
    COALESCE(TRY_TO_NUMBER(assist_tackle), 0)::boolean as assist_tackle,
    COALESCE(TRY_TO_NUMBER(lateral_reception), 0)::boolean as lateral_reception,
    COALESCE(TRY_TO_NUMBER(lateral_rush), 0)::boolean as lateral_rush,
    COALESCE(TRY_TO_NUMBER(lateral_return), 0)::boolean as lateral_return,
    COALESCE(TRY_TO_NUMBER(lateral_recovery), 0)::boolean as lateral_recovery,
    passer_player_id,
    passer_player_name,
    passing_yards,
    receiver_player_id,
    receiver_player_name,
    receiving_yards,
    rusher_player_id,
    rusher_player_name,
    coalesce(try_to_number(rushing_yards, 0), 0) AS rushing_yards
    lateral_receiver_player_id,
    lateral_receiver_player_name,
    lateral_receiving_yards,
    lateral_rusher_player_id,
    lateral_rusher_player_name,
    lateral_rushing_yards,
    lateral_sack_player_id,
    lateral_sack_player_name,
    interception_player_id,
    interception_player_name,
    lateral_interception_player_id,
    lateral_interception_player_name,
    punt_returner_player_id,
    punt_returner_player_name,
    lateral_punt_returner_player_id,
    lateral_punt_returner_player_name,
    kickoff_returner_player_name,
    kickoff_returner_player_id,
    lateral_kickoff_returner_player_id,
    lateral_kickoff_returner_player_name,
    punter_player_id,
    punter_player_name,
    kicker_player_name,
    kicker_player_id,
    own_kickoff_recovery_player_id,
    own_kickoff_recovery_player_name,
    blocked_player_id,
    blocked_player_name,
    tackle_for_loss_1_player_id,
    tackle_for_loss_1_player_name,
    tackle_for_loss_2_player_id,
    tackle_for_loss_2_player_name,
    qb_hit_1_player_id,
    qb_hit_1_player_name,
    qb_hit_2_player_id,
    qb_hit_2_player_name,
    forced_fumble_player_1_team,
    forced_fumble_player_1_player_id,
    forced_fumble_player_1_player_name,
    forced_fumble_player_2_team,
    forced_fumble_player_2_player_id,
    forced_fumble_player_2_player_name,
    solo_tackle_1_team,
    solo_tackle_2_team,
    solo_tackle_1_player_id,
    solo_tackle_2_player_id,
    solo_tackle_1_player_name,
    solo_tackle_2_player_name,
    assist_tackle_1_player_id,
    assist_tackle_1_player_name,
    assist_tackle_1_team,
    assist_tackle_2_player_id,
    assist_tackle_2_player_name,
    assist_tackle_2_team,
    assist_tackle_3_player_id,
    assist_tackle_3_player_name,
    assist_tackle_3_team,
    assist_tackle_4_player_id,
    assist_tackle_4_player_name,
    assist_tackle_4_team,
    tackle_with_assist,
    tackle_with_assist_1_player_id,
    tackle_with_assist_1_player_name,
    tackle_with_assist_1_team,
    tackle_with_assist_2_player_id,
    tackle_with_assist_2_player_name,
    tackle_with_assist_2_team,
    pass_defense_1_player_id,
    pass_defense_1_player_name,
    pass_defense_2_player_id,
    pass_defense_2_player_name,
    fumbled_1_team,
    fumbled_1_player_id,
    fumbled_1_player_name,
    fumbled_2_player_id,
    fumbled_2_player_name,
    fumbled_2_team,
    fumble_recovery_1_team,
    fumble_recovery_1_yards,
    fumble_recovery_1_player_id,
    fumble_recovery_1_player_name,
    fumble_recovery_2_team,
    fumble_recovery_2_yards,
    fumble_recovery_2_player_id,
    fumble_recovery_2_player_name,
    sack_player_id,
    sack_player_name,
    half_sack_1_player_id,
    half_sack_1_player_name,
    half_sack_2_player_id,
    half_sack_2_player_name,
    return_team,
    return_yards,
    penalty_team,
    penalty_player_id,
    penalty_player_name,
    penalty_yards,
    replay_or_challenge,
    replay_or_challenge_result,
    penalty_type,
    defensive_two_point_attempt,
    defensive_two_point_conv,
    defensive_extra_point_attempt,
    defensive_extra_point_conv,
    safety_player_name,
    safety_player_id,
    season,
    cp as completion_probability,
    cpoe as completion_probability_over_expectation,
    series,
    series_success,
    series_result,
    order_sequence,
    start_time,
    time_of_day,
    stadium,
    weather,
    nfl_api_id,
    play_clock,
    COALESCE(TRY_TO_NUMBER(play_deleted), 0)::boolean as play_deleted,
    play_type_nfl,
    COALESCE(TRY_TO_NUMBER(special_teams_play), 0)::boolean as special_teams_play,
    st_play_type as special_teams_play_type,
    end_clock_time,
    end_yard_line,
    fixed_drive,
    fixed_drive_result,
    drive_real_start_time,
    drive_play_count,
    drive_time_of_possession,
    drive_first_downs,
    COALESCE(TRY_TO_NUMBER(drive_inside20), 0)::boolean as drive_inside20,
    COALESCE(TRY_TO_NUMBER(drive_ended_with_score), 0)::boolean as drive_ended_with_score,
    drive_quarter_start,
    drive_quarter_end,
    drive_yards_penalized,
    drive_start_transition,
    drive_end_transition,
    drive_game_clock_start,
    drive_game_clock_end,
    drive_start_yard_line,
    drive_end_yard_line,
    drive_play_id_started,
    drive_play_id_ended,
    away_score,
    home_score,
    location,
    result as home_point_differential,
    total as total_points_scored,
    spread_line as closing_spread_line,
    total_line as closing_total_line,
    COALESCE(TRY_TO_NUMBER(div_game), 0)::boolean as div_game,
    roof,
    surface,
    temp,
    wind,
    home_coach,
    away_coach,
    stadium_id,
    game_stadium,
    success,
    passer,
    passer_jersey_number,
    rusher,
    rusher_jersey_number,
    receiver,
    receiver_jersey_number,
    COALESCE(TRY_TO_NUMBER(pass), 0)::boolean as pass,
    COALESCE(TRY_TO_NUMBER(rush), 0)::boolean as rush,
    COALESCE(TRY_TO_NUMBER(first_down), 0)::boolean as first_down,
    COALESCE(TRY_TO_NUMBER(aborted_play), 0)::boolean as aborted_play,
    COALESCE(TRY_TO_NUMBER(special), 0)::boolean as special_play,
    COALESCE(TRY_TO_NUMBER(play), 0)::boolean as normal_play,
    passer_id,
    rusher_id,
    receiver_id,
    name as qb_or_rb_name,
    jersey_number,
    id as qb_or_rb_id,
    fantasy_player_name,
    fantasy_player_id,
    fantasy,
    fantasy_id,
    COALESCE(TRY_TO_NUMBER(out_of_bounds), 0)::boolean as out_of_bounds,
    COALESCE(TRY_TO_NUMBER(home_opening_kickoff), 0)::boolean as home_opening_kickoff,
    qb_epa,
    xyac_epa,
    xyac_mean_yardage,
    xyac_median_yardage,
    xyac_success,
    xyac_fd,
    xpass,
    pass_oe
from src_historical_play_by_play