dbtfpxp:
  outputs:
    dev:
      account: "{{ env_var('dbt_snowflake_account') }}"
      database: football_play_by_play
      password: "{{ env_var('dbt_password') }}"
      role: "{{ env_var('dbt_role') }}"
      schema: raw
      threads: 1
      type: snowflake
      user: "{{ env_var('dbt_user') }}"
      warehouse: "{{ env_var('dbt_warehouse') }}"
  target: dev